### ISSUE TITLE
TypeError: splits() missing 1 required positional argument: 'label_field'

### ISSUE THREAD

**Issue by Jasperty** [schelotto/Neural_Speed_Reading_via_Skim-RNN_PyTorch#1]
when i run main.py， i got this error：

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    train_iter, test_iter = load_data(text_field, label_field, device=-1, repeat=False)
  File "main.py", line 47, in load_data
    train_data, test_data = dataset.splits(text_field, label_field)
TypeError: splits() missing 1 required positional argument: 'label_field'

**Comment by schelotto** [comment]
It's a bug coming from my old code.  It was cleaned up now. Thanks.
